:CSname: PROJJSON
:Title: {CSname} Community Standard Work Item Justification
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    YY-nnnrx
|Category: OGC(R) Community Standard Work Item Justification
|Authors:   <Name(s) of Editor or Editors>
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) <year> Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This document provides a justification to the OGC Technical Committee (TC) for consideration of {CSname} as a Community standard. This justification, along with the submitted candidate Community standard, will form the basis for TC review and vote to approve the start of a Work Item as the first step in the Community standard process for this standard.

The submitters agree to abide by the TC Policies and Procedures and OGC Intellectual Property Rights Policy (http://www.opengeospatial.org/ogc/policies) during the processing of this submission.

Once approved, the Community standard Work Item defined by this document is valid for six (6) months.

== Overview of proposed submission

////
Summarize the proposed Community standard. In this summary, provide an overview of the geospatial interoperability requirements the proposed standard supports, the history of its development and use, and use cases.
////

https://proj.org/specifications/projjson.html[PROJJSON] is a https://www.json.org/json-en.html[JSON encoding] of http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[WKT2:2019 / ISO-19162:2019: Geographic information - Well-known text representation of coordinate reference system], which itself implements the model of http://docs.opengeospatial.org/as/18-005r4/18-005r4.html[OGC Topic 2: Referencing by coordinates abstract specification / ISO-19111:2019]. Apart from the difference of encodings, the semantics is intended to be exactly the same as WKT2:2019, and PROJJSON can be morphed losslessly from/into WKT2:2019.

PROJJSON is aimed at encoding definitions of coordinate reference systems (CRS), and their composing objects: datums, datum ensembles, coordinate systems, conversion, and coordinate operations.

PROJJSON was first implemented in version 6.2 of the https://proj.org[PROJ] open-source library (released in September 2019).

The rationale for the development of PROJJSON is that the use of WKT strings in JSON documents or JSON-based APIs is awkward, as the parsing of WKT strings require non-trivial logic which strong domain knowledge of CRS modeling. Having a dedicated JSON encoding for CRS makes it easier for consumers to inspect properties of a CRS, like its nature, name, units, identifiers, etc. much easier by simple natification in the JSON object hierarchy.

PROJJSON comes with a JSON schema [https://proj.org/schemas/v0.7/projjson.schema.json] which helps writers of PROJJSON to validate the well-formedness of their output, and consumers to have the grammar of PROJJSON content in a well-accepted format.

== Relationship to other OGC Standards

////
State whether this proposed Community standard has any dependencies on OGC standards or is itself normatively referenced by an OGC standard and list those standards, as applicable.
////

PROJJSON is a JSON encoding of http://docs.opengeospatial.org/as/18-005r4/18-005r4.html[OGC Topic 2: Referencing by coordinates abstract specification / ISO-19111:2019], and can be morphed from/into http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[WKT2:2019].

It is used as the CRS encoding for the https://github.com/opengeospatial/geoparquet/blob/main/format-specs/geoparquet.md#crs[GeoParquet specification]. The Apache Parquet provides a standardized open-source columnar storage format. The GeoParquet specification defines how geospatial data should be stored in parquet format, including the representation of geometries and the required additional metadata.

PROJJSON is used in the https://docs.opengeospatial.org/DRAFTS/17-083r4.html#tms-json-encoding[OGC Two Dimensional Tile Matrix Set and Tile Set Metadata] for its JSON encoding.

It is also considered for use in the CoverageJSON standard (https://github.com/opengeospatial/CoverageJSON/issues/26) or potential future work item for OGC API features (https://github.com/opengeospatial/ogcapi-features/issues/451#issuecomment-719403423)

== Alignment with OGC Standards Baseline

////
Describe where this proposed standard fits with respect to the existing OGC standards baseline and standards in development in the OGC and whether this proposed standard may compete with or enhance an existing OGC standard.
////

PROJJSON has been developped and adopted several years before the ongoing work by the OGC CRS SWG on a OGC CRS JSON standard at https://github.com/opengeospatial/CRS-JSON-Encoding for which there is still no public draft. Given the lack of such draft more than one year and a half after the work has started, it is difficult to comment on the differences between the two approaches.

== Evidence of implementation

The following implementations use the proposed Community standard.

////
Repeat for each implementation. Place a "x" in the appropriate box regarding complete implementation.
Optionally, provide a narrative description of the extent of implementation of the proposed Community standard for those proposed standards that are very widely used.
////

=== PROJ library

*Implementation name:* PROJ library

*Date of most recent version:* PROJ 9.7.0, October 1st 2025s

*Implementation description:*

PROJ is a generic coordinate transformation C++ library that transforms geospatial coordinates from one coordinate reference system (CRS) to another. This includes cartographic projections as well as geodetic transformations. PROJ is released under the MIT open source license. PROJ is used in many open-source software (GDAL, QGIS, GRASS-GIS, pyproj, PROJ-JNI, etc.), as well as in commercial software.

It offers import and export capabilities of PROJJSON from/to WKT2:2019 (or earlier versions).

It is the initial, and probably what can be considered the reference implementation of PROJJSON.

*Implementation URL:* https://proj.org

*Is implementation complete?*

* [x] Yes
* [ ] No

*If not,* what portions of the proposed Community standard are implemented?

=== pyproj library

*Implementation name:* pyproj library

*Date of most recent version:* pyproj 3.7.2, August 14th 2025

*Implementation description:*

Python interface to PROJ (cartographic projections and coordinate transformations library).

Supports PROJJSON since its version 2.5.0 (February 2020)

*Implementation URL:* https://pyproj4.github.io/pyproj

*Is implementation complete?*

* [x] Yes
* [ ] No

*If not,* what portions of the proposed Community standard are implemented?

=== PROJJSON to WKT conversion script

*Implementation name:* projjson_to_wkt

*Date of most recent version:* projjson_to_wkt 1.0.0, October 31th 2025

Converts a PROJJSON CRS string into a WKT CRS string (WKT1 or WKT2:2019 variants supported).

A JavaScript port of it exists at https://github.com/m-mohr/projjson_to_wkt

*Implementation URL:* https://github.com/rouault/projjson_to_wkt

*Is implementation complete?*

* [x] Yes
* [ ] No

*If not,* what portions of the proposed Community standard are implemented?

=== Usage by other standards, specifications or online resources

==== STAC Proj extension

PROJJSON is one of the CRS encoding supported by the https://github.com/stac-extensions/projection[SpatioTemporal Asset Catalog (STAC) Projection Extension].

==== GeoParquet format

PROJJSON is the only CRS encoding supported by the https://geoparquet.org/releases/v1.1.0/[GeoParquet 1.1.0 format specification]

==== Parquet GEOMETRY/GEOGRAPHY column type

PROJJSON is one the CRS encoding supported by the https://github.com/apache/parquet-format/blob/master/Geospatial.md#crs-customization[Parquet GEOMETRY/GEOGRAPHY column type]

==== GDAL Zarr driver

PROJJSON is supported in read and write as one of the potential encodings for CRS in the https://gdal.org/drivers/raster/zarr.html#srs-encoding[GDAL Zarr driver], developed as part of http://docs.opengeospatial.org/per/21-032.html#toc23[OGC Testbed 17]

==== ESA Earth Observation Platform (EOPF) Zarr Visualization product

PROJJSON is  one the CRS encoding supported by the https://github.com/zarr-experimental/geo-proj["geo-proj" Zarr extension].

==== spatialreference.org web site

https://spatialReference.org[spatiareference.org] is a comprehensive online resource dedicated to providing detailed information and reference materials on spatial coordinate reference systems. It supports PROJJSON as one of the formats.

== Public availability

Is the proposed Community standard currently publicly available?

* [x] Yes
* [ ] No

URL: https://proj.org/specifications/projjson.html

The PROJJSON specification and JSON schema are available under the MIT license.

== Supporting OGC Members

////
List the supporting organizations. There must be at least three OGC organizations of which at least one must be an OGC Voting Member.
////

- OSGeo

== Intellectual Property Rights

Will the contributor retain intellectual property rights?

* [x] Yes
* [ ] No

If yes, the contributor will be required to work with OGC staff to properly attribute the submitter’s intellectual property rights.

If no, the contributor will assign intellectual property rights to the OGC.
